apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: event-management-system-react-app-dep
spec:
  selector:
    matchLabels:
      app: event-management-system-react-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: event-management-system-react-app
    spec:
      containers:
        - name: event-management-system-react-app
          image: yesubauboyena/event-management-system-react-app:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173 # The port that the container is running on in the cluster